
def build(bld):
   defines = ''
   features = []
   if bld.options.submission:
      defines = 'ONLINE_JUDGE'

   # ext_paths = ['/usr/lib/i386-linux-gnu', '/usr/lib/x86_64-linux-gnu']
   # bld.read_shlib('pthread', paths = ext_paths)
   bld.program(features = 'cxx programrunner',
				   use = 'gtest',
               uselib ='pthread',
				   include = ['.'],
				   source = bld.path.ant_glob('*.cxx'),
				   defines = defines,
				   target = '3n+1Problem')


