#!/usr/bin/env python

import sys

name = None

def processArgs():
   if len(sys.argv) != 2:
      printUsage()

   if sys.argv[1] == '-h' or sys.argv[1] == '--help':
      printUsage()

   name = sys.argv[1]
   print name

def makeDirectory():
   pass

def makeSampleFiles():
   pass

def makeSourceFile():
   pass

def makeTestFile():
   pass

def makeWscript():
   pass

def printUsage():
   sys.exit()

if __name__ == "__main__":
   processArgs()
   makeDirectory()
   makeSampleFiles()
   makeSourceFile()
   makeTestFile()
   makeWscript()